
programa: manager pa pb pc pd daemon

manager: 
	gcc manager.c -o manager

pa: 
	gcc pa.c -o pa

pb:
	gcc pb.c -o pb

pc:
	gcc pc.c -o pc

pd:
	gcc pd.c -o pd

daemon:
	gcc daemon.c -o daemon

clean:
	rm daemon manager pa pb pc pd


